### ISSUE TITLE
Updating 2.5.3 to 2.6.2 breaks url() view helper, "No RouteStackInterface instance provided"

### ISSUE THREAD

**Issue by TwoWholeWorms** [zendframework/zend-view#51]
About an hour or so ago I did a `composer update` which included an automatic update for this module from 2.5.3 to 2.6.2. After this update was installed, the `url()` view helper fatally stopped working as `null === $this->router`, which caused it to throw `Exception\RuntimeException('No RouteStackInterface instance provided')` from `Zend\View\Helper\Url` at line 54.

Unfortunately, that's all I've got at the moment as I haven't had a chance to dig deeper into what's actually causing the problem, but I'm hoping someone will have an idea from this. That said, I am specifically requiring `"zendframework/zendframework": "2.5.*"` in `composer.json`, so it could be a version incompatibility? I've added a require line to force `"zendframework/zend-view": "2.5.*"` which has resolved the issue for me at least for the time being.

**Comment by stefanorg** [comment]
i can confirm, it also happen to me from 2.5.3 to 2.6.2.

**Comment by weierophinney** [comment]
I've isolated the issue.

In versions prior to 2.6, we define `$invokableClasses`. To make these forwards compatible with version 3, we split all `$invokableClasses` entries into `$aliases` and `$factories` entries (with the latter using the new `Zend\ServiceManager\Factory\InvokableFactory`). The factory keys are fully qualified class names, while the aliases are the "short" names.

What this means is that `url` is an alias to `Zend\View\Helper\Url` within the helper plugin manager. However, in zend-mvc, we define an override factory that ensures that the route match and router are injected. The problem? It uses the key "url", and, since an alias *also* exists with that same name, the alias is resolved. As such, the override factory is never invoked.

I'm going to open a new issue on zend-mvc to address this.

**Comment by weierophinney** [comment]
I have a patch ready at zendframework/zend-mvc#71.

Could one of those of you who are affected by the issue please test? You can do so as follows:

1. Add my repo to your `composer.json`: 

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/weierophinney/zend-mvc.git"
    }
],
```

2. Add an override for the zend-mvc dependency to your `composer.json`:

```json
"require": {
    "zendframework/zend-mvc": "dev-hotfix/71 as 2.6.2"
}
```

3. Update your dependencies:

```console
$ composer update zendframework/zend-mvc
```

You should see that composer installs from my repo at that point.

Then let me know if the patch works!

**Comment by ThaDafinser** [comment]
Had the same issue.

Solving it without rewrite your own code would require to add the line below with comment
![image](https://cloud.githubusercontent.com/assets/533017/14701519/1b81a848-07a6-11e6-849a-7478ea1df460.png)

To avoid it in the meantime, it's possible to create a own factory with the code from here
![image](https://cloud.githubusercontent.com/assets/533017/14701563/4e9fbf62-07a6-11e6-8f20-052e6e792400.png)

**Comment by ThaDafinser** [comment]
@TwoWholeWorms @stefanorg how you guys solved it?

Also with a similar "hack" like i posted above? Or something elese?
