### ISSUE TITLE
ServerUrl helper doesn't work with console requests

### ISSUE THREAD

**Issue by countless-integers** [zendframework/zend-view#6]
[This line](https://github.com/zendframework/zend-view/blob/master/src/Helper/ServerUrl.php#L59) makes it impossible for the helper to work in console requests made by zend controller tests as this key is not set in cli.

**Comment by weierophinney** [comment]
Why are you passing boolean `true` to the helper?

TBH, the entire helper is unusable in a console request *unless you seed it with defaults*. The helper defines a number of setter methods you can use in order to do this, and I'd argue it's not the framework's responsibility to seed those values when used under a console request, but the *application developer's*.

(Full disclosure: I've successfully used the helper in [PhlyBlog](https://github.com/phly/PhlyBlog), which generates a static blog from the command line. In other words, I've done *exactly* what I suggest above.)

**Comment by countless-integers** [comment]
To be honest I just need a way to obtain the full request url, that's why I turned to `serverUrl(true)`. I get it that the domain would have to be set, but the uri part could be generated. `url` helper can generate most of it (with `force_canonical` option), but as far as I know there's no convenient way to tell it reuse query params (same as it can reuse route params).

I'm am unable to find a singe call to `ServerUrl` in PhlyBlog. Could you be so kind and point me to it?
